RWTH-EBC/FiLiP

tests/clients/test_ngsi_v2_timeseries.py
test_ngsi_v2_timeseries.py had already a tear down to remove subscriptions. But it did only remove a selection of them. 
Now the test suite clears all subscriptions after each test, and ensures the existence of both needed entities, and their clean-up.
=> State setup and clean teardown

filip/clients/ngsi_v2/cb.py, filip/utils/cleanup.py, requirements.txt, tests/clients/test_ngsi_v2_iota.py
Test deletion fixed.
I saw that the use of delete_entity for all entity was much slower than using the batch methode (16s to 6s).
Therefore I implented a methode that can also be used by endusers to efficiently delete entities as batch.
The methode calls update(delete) twice (with controlled logic)
Additionally I removed a few clean-all() class that were redundant, as each test calls it in the tear_down
=> fix: 69 test clean up uses wrong method to clean entities

CHANGELOG.md, examples/orion_example.py, examples/registration_example.py, filip/clients/ngsi_v2/cb.py, filip/clients/ngsi_v2/iota.py, filip/models/ngsi_v2/context.py, tests/clients/test_ngsi_v2_cb.py, tests/clients/test_ngsi_v2_iota.py, tests/models/test_ngsi_v2_context.py
I added the Patch device method and the tests as described in issue 74.
I discovered that Patch Entity and the context model changes were not yet live on development and only local in #30. 
I therefore bundled here all these changes to be reviewed together.
The made changes can be summarized as:
- Patch Methods (Device and Entity)
- ContextEntity Remodel (to make attribute interface more clear to the user)
- Helper functions (does entity/device exists ?)
- Test functions to test new and a few old uncovered methods
- Change of comments to make functionality more clear
=> Feat: Patch Methods

examples/semantics/semantics_model_example.py, filip/semantics/semantics_manager.py, filip/semantics/semantics_models.py, filip/semantics/vocabulary_configurator.py, tests/semantics/test_semantics_models.py
Added feature, tests, documentation.
I created the metadata attribute in the SemanticClass. 
This name works neatly as a ContextEntity itself does not possess metadata, and these information can be considered metadata.
This form adds minimal difference, and is easily extendable if in the future more information should be kept as metadata.
=> Added Semantic instance metadata

filip/clients/ngsi_v2/quantumleap.py, filip/utils/cleanup.py
I removed the unneeded sleeps from the clean-up function, and ensured that the delete works as intended.
For the QL, i added a limited counter loop in the delete function, as tests showed that multiple tries were needed until the deletion was completed. 
Currently there seems to be a small chance 1/10 that even after all deletes were detected as successful, the QL still finds entries. I currently do not know the cause, but as it does not impact any tests, I "ignored" it now for the moment
=> Improved Test Cleanup

filip/models/ngsi_v2/context.py
Filtered commands from get_properties according to the new command logic:
A command is not defined by the DataType.Command but if it has the two auto-generated siblings: _info and _status
=> Fix: Filtered Commands

CHANGELOG.md, filip/clients/ngsi_v2/cb.py, filip/clients/ngsi_v2/iota.py, filip/utils/iot.py, tests/clients/test_ngsi_v2_cb.py, tests/clients/test_ngsi_v2_iota.py
Since the IoTAgent API does not provide filter functionality, I implement this in the IoTAgentClient of FiLiP. In this way the function get_device_list( ) can now return the devices filtered by entity_id.
=> 143 unrelevant devices get deleted by cb delete entity

tests/clients/test_ngsi_v2_timeseries.py
I added a simple test for throttling in subscriptions. Please have a look at whether this is conforming to your existing testing.
=> Add Test for throttling in subscription

.gitignore, CHANGELOG.md, filip/clients/ngsi_v2/cb.py, tests/clients/test_ngsi_v2_cb.py
For #157
In the new orion version from 3.6.0 the update semantics of attribute metadata has introduced a breaking change. Also see: https://github.com/telefonicaid/fiware-orion/issues/4033 and https://fiware-orion.readthedocs.io/en/master/user/metadata.html#updating-metadata
=> fix: added override_metadata args to patch_entity

filip/clients/ngsi_v2/cb.py, tests/clients/test_ngsi_v2_cb.py
Fix issue with string format. The old version is escaped with \ . This results in an error when sending a string value to fiware
=> fix: remove additional escape chars when sending a string

filip/models/ngsi_v2/base.py, tests/models/test_ngsi_v2_base.py
Changed the line as proposed in the issue definition.
=> fix: bug in typePattern validation

filip/models/base.py
=> fix: updated regex to pattern

CHANGELOG.md, tests/clients/test_ngsi_v2_cb.py, tests/config.py
=> feat: add mqtt internal url in tests

CHANGELOG.md, examples/README.md, examples/ngsi_v2/e12_ngsi_v2_use_case_models.py, filip/clients/ngsi_v2/cb.py, filip/models/ngsi_v2/context.py, tests/clients/test_mqtt_client.py, tests/clients/test_ngsi_v2_cb.py
=> 262 support entity creation with keyvalues

CHANGELOG.md, filip/clients/ngsi_v2/cb.py, filip/utils/cleanup.py, tests/clients/test_ngsi_v2_cb.py, tests/clients/test_ngsi_v2_iota.py
Closes #265. Test involves clear methods that are subsequently used by the teardown method, so i added a try , except at the teardown but maybe someone should have a better look into that.
=> 265 order in cleanup function

CHANGELOG.md, filip/clients/ngsi_v2/cb.py, tests/clients/test_ngsi_v2_cb.py
Closes #145 Update Relationships with ContextBrokerClient update_entity. Implemented as suggested in the issue. The test is standalone for now but maybe it should be incorporated in the update_entity case of test_entity_update ?
=> 145 update relationships with contextbrokerclient update entity

examples/ngsi_v2/e04_ngsi_v2_context_subscriptions_mqtt.py, examples/ngsi_v2/e08_ngsi_v2_iota_paho_mqtt.py, examples/ngsi_v2/e09_ngsi_v2_iota_filip_mqtt.py, filip/clients/mqtt/client.py, filip/clients/ngsi_v2/cb.py, filip/clients/ngsi_v2/iota.py, requirements.txt, setup.py, tests/clients/test_mqtt_client.py, tests/clients/test_ngsi_v2_cb.py, tests/models/test_ngsi_v2_iot.py, tutorials/ngsi_v2/e1_virtual_weatherstation/e1_virtual_weatherstation_solution.py
Closes #272 
Closes #270 
I also removed a redundant warning in the subscription handling, which leads to this messages:
```
18-Apr-2024 12:32:58 INFO: pong/NotifiedAttributesContextBroker: Posting subscription to topic '/agentlib/agentlib/myEmulatorExample/ContextBrokerSubscriptions/pong_NotifiedAttributesContextBroker' with sub'={"id":null,"description":"pong_NotifiedAttributesContextBroker","status":"active","subject":{"entities":[{"id":"ping_entity","idPattern":null,"type":"sensor","typePattern":null}],"condition":{"attrs":["ping_attribute"],"expression":null}},"notification":{"timesSent":null,"http":null,"httpCustom":null,"mqtt":{"url":"mqtt://134.130.56.157:1883","topic":"/agentlib/agentlib/myEmulatorExample/ContextBrokerSubscriptions/pong_NotifiedAttributesContextBroker/ping_entity" …
```
=> 272 mqtt v2 does not work

.coveragerc, docs/source/examples.rst, examples/README.sphinx.md
=> 306 example is not correctly linked in documentation

filip/models/ngsi_v2/subscriptions.py, tests/clients/test_ngsi_v2_cb.py, tests/models/test_ngsi_v2_subscriptions.py
The following warning pops up "UserWarning: Field name "json" shadows an attribute in parent "Mqtt"" ( due to the json fields in MqttCustom and HttpCustom ). Since the Http/Mqtt models do not have an explicit json field, i take it this is coming from some field/property in the base model.
Tried to circumvent the warning by the use of aliases which obviously did not work.
Not sure what model to specify for the json payload type, i just put a Dict[str, any] for now ( despite number/string being valid json , the orion manual specifies that it needs to be a JSON object and not an object of primitive type )
Any input on these two points is welcome.
=> 288 filip support right now only paylaod in mqtt custom / http custom but orion already supports json and ngsi as further options

CHANGELOG.md, filip/models/ngsi_v2/base.py
=> 203 non existing attribute is returned and causes float conversion error

tests/README.md
=> docs: update the readme for running unittest

filip/models/ngsi_ld/context.py, tests/models/test_ngsi_ld_context.py
=> 221 ngsi ld migrate v2 datamodels in ld

filip/clients/ngsi_ld/cb.py, filip/models/__init__.py, filip/models/ngsi_ld/subscriptions.py, filip/utils/cleanup.py, tests/clients/test_ngsi_ld_cb.py, tests/clients/test_ngsi_ld_entity_batch_operation.py, tests/clients/test_ngsi_ld_subscription.py, tests/models/test_ngsi_ld_subscriptions.py, tests/utils/test_clear.py
=> 342 clean up functions for ngsi ld context broker

filip/clients/ngsi_v2/cb.py
=> fix error handling in cb.py

filip/clients/ngsi_ld/cb.py, filip/clients/ngsi_v2/cb.py, filip/clients/ngsi_v2/iota.py, tests/clients/test_ngsi_v2_client.py
=> 377 fix error handling in context broker client

CHANGELOG.md, README.md, filip/__init__.py, setup.py
=> 391 release preparation v0 6 1

filip/clients/ngsi_ld/cb.py, tests/clients/test_ngsi_ld_cb_kv.py
There might still be some redundancies
=> 384 ngsi ld support for entity creation and update with keyvalues format

.github/ISSUE_TEMPLATE/release_prepare.md, CHANGELOG.md, filip/__init__.py, setup.py
=> 404 release preparation v062

filip/clients/ngsi_ld/cb.py, tests/clients/test_ngsi_ld_cb.py
Logic behind this is: Attr will only either have a value field or an object field. We pull the update value from the corresponding field by checking if `'value' in attr.model_dump()`, if not we pass object. Whether the actual value is falsy becomes completely irrelevant
=> fix: falsy value handling on update_entity_attribute
