RWTH-EBC/FiLiP

- docs/source/conf.py
- filip/__init__.py
- filip/clients/base_http_client.py
- setup.py
- tests/clients/test_ngsi_v2_cb.py
- tests/clients/test_ngsi_v2_client.py
- tests/clients/test_ngsi_v2_iota.py
- tests/clients/test_ngsi_v2_timeseries.py
> fixed bug in client logging

- docs/source/conf.py
- filip/__init__.py
- filip/models/base.py
- filip/models/ngsi_v2/context.py
- filip/models/ngsi_v2/units.py
- filip/utils/validators.py
- requirements.txt
- setup.py
- tests/models/test_units.py
> 10 make loading units a function

- docs/source/conf.py
- filip/__init__.py
- filip/clients/base_http_client.py
- setup.py
> 12 fiware service returns path

- CHANGELOG.md
- docs/source/conf.py
- filip/__init__.py
- filip/models/base.py
- filip/models/ngsi_v2/context.py
- filip/models/ngsi_v2/iot.py
- setup.py
- tests/models/test_ngsi_v2_context.py
- tests/models/test_ngsi_v2_iot.py
Now the fields are really FIWARE safe. 
In two cases I shortened the regex, but as far as I saw (and the text stateted) these limitations were not needed for these fields. * is an allowed char.
> Changed all Regexes to disallow spaces

- filip/models/ngsi_v2/iot.py
Add "autoprovision" to the class ServiceGroup
> Add "autoprovision" to the class ServiceGroup

- filip/semantics/vocabulary_configurator.py
I implemented the feature, and adapted the method description
> feat: Semantics: Flexible model generation

- examples/semantics/semantics_model_example.py
- filip/semantics/semantics_manager.py
- tests/semantics/test_semantics_models.py
As requested I implemented a search function for the semantic classes/models.
A test was added as well as an entry into the examples.
> feat: Semantic Model Search

- filip/utils/cleanup.py
> Fix: added missing decorator

- examples/semantics/semantics_model_example.py
- examples/semantics/semantics_vocabulary_example.py
- filip/clients/ngsi_v2/cb.py
- filip/models/ngsi_v2/iot.py
- filip/semantics/ontology_parser/post_processer.py
- filip/semantics/ontology_parser/rdfparser.py
- filip/semantics/ontology_parser/vocabulary_builder.py
- filip/semantics/semantics_manager.py
- filip/semantics/semantics_models.py
- filip/semantics/vocabulary/entities.py
- filip/semantics/vocabulary/relation.py
- filip/semantics/vocabulary/source.py
- filip/semantics/vocabulary_configurator.py
- tests/semantics/models.py
- tests/semantics/models2.py
- tests/semantics/test_semantics_models.py
Fixed the mentioned issue.
Also added a quick fix for two tests that were failing depending on the runtime environment (as the cb-client used the environment url)
> Fix: Fixed header loading

- CHANGELOG.md
- filip/clients/mqtt/client.py
- setup.py
See #124 for info, here only relevant changes are merged
> chore: Only push relevant changes

- filip/clients/ngsi_v2/cb.py
- filip/utils/filter.py
- tests/clients/test_ngsi_v2_cb.py
- tests/utils/test_filter.py
> feat: added function get_subscriptions_by_entity with test

- README.md
- filip/models/ngsi_v2/subscriptions.py
> chore: came up with simpler solution to validator

- CHANGELOG.md
- filip/clients/ngsi_v2/cb.py
- filip/models/ngsi_v2/subscriptions.py
- tests/models/test_ngsi_v2_subscriptions.py
> 154 new flag only changed attrs of cb subscription

- LICENSE.md
- README.md
- docs/source/conf.py
- setup.py
> Release: updated all meta information

- CHANGELOG.md
- filip/clients/ngsi_v2/cb.py
- filip/semantics/semantics_manager.py
- tests/clients/test_ngsi_v2_cb.py
> fix: misleading log for does_entity_exist

- CHANGELOG.md
> 176 prepare release v0 2 4

- filip/clients/ngsi_v2/iota.py
- tests/clients/test_ngsi_v2_iota.py
> 170 edit service group not work

- filip/clients/ngsi_v2/iota.py
- filip/utils/filter.py
- tests/clients/test_ngsi_v2_iota.py
> 169 service group can not be retrieved by apikey and resource

- filip/models/ngsi_v2/context.py
- tests/models/test_ngsi_v2_context.py
> 182 get attributes will only return the attributes with the pre defined attribute type

- CHANGELOG.md
- setup.py
> prepare release v0 2 5

- .gitlab-ci.yml
- filip/clients/mqtt/client.py
- filip/clients/ngsi_v2/iota.py
- filip/models/ngsi_v2/context.py
- filip/models/ngsi_v2/iot.py
- filip/semantics/semantics_models.py
> feat: add messages to all KeyErrors

- CHANGELOG.md
- filip/clients/ngsi_v2/iota.py
The error-msg should not be "could not update" but "post" devices, as the function is post devices.
> Fix wrong msg in iota.py

- filip/models/base.py
- filip/models/ngsi_ld/context.py
- tests/models/test_ngsi_ld_context.py
> 220 ngsi ld testcases for ld data models

- CHANGELOG.md
- filip/models/ngsi_v2/iot.py
- tests/models/test_ngsi_v2_iot.py
> 178 error on duplicate object

- .coveragerc
- .gitlab-ci.yml
- README.md
- docs/requirements.txt
- docs/source/conf.py
> fix outdated gitlab pages

- tests/models/test_ngsi_v2_subscriptions.py
> test: implement test for macro substitution

- CHANGELOG.md
- filip/models/ngsi_v2/subscriptions.py
- tests/clients/test_ngsi_v2_cb.py
- tests/models/test_ngsi_v2_subscriptions.py
> 298  covered field for more general notifications that cover multiple entity types see here

- CHANGELOG.md
- filip/__init__.py
- setup.py
> release v0.5.0

- examples/ngsi_v2/e12_ngsi_v2_use_case_models.py
- filip/clients/ngsi_v2/cb.py
- tests/clients/test_ngsi_v2_cb.py
> 281 intergrade the key values endpoints with the normal ones

- examples/ngsi_v2/e14_ngsi_v2_notification_based_command.py
- filip/models/ngsi_v2/subscriptions.py
> 289 add example for notification based command

- filip/clients/ngsi_ld/cb.py
- filip/models/base.py
- filip/models/ngsi_ld/context.py
- setup.py
- tests/clients/test_ngsi_ld_cb.py
- tests/clients/test_ngsi_ld_entity_batch_operation.py
> 339 test link header for ld

- filip/clients/ngsi_ld/cb.py
- filip/models/ngsi_ld/context.py
- tests/clients/test_ngsi_ld_cb.py
- tests/models/test_ngsi_ld_context.py
> 356 post entity has an unused variable update need to check the spec for the expected behavior

- filip/models/ngsi_ld/context.py
> chore: remove deprecated functions in NGSI-LD models

- CHANGELOG.md
- filip/clients/ngsi_v2/cb.py
- tests/clients/test_ngsi_v2_cb.py
> feat: add relationship validation method for v2 cbc

- CHANGELOG.md
- filip/models/ngsi_ld/context.py
- tests/clients/test_ngsi_ld_cb.py
> 410 ngsi ld relationship cannot be created via context relationship

- CHANGELOG.md
- filip/clients/ngsi_ld/cb.py
- tests/clients/test_ngsi_ld_cb.py
> 385 ngsild post entity ignore unset properties

- CHANGELOG.md
- filip/clients/ngsi_v2/cb.py
- tests/clients/test_ngsi_v2_cb.py
> fix: allow none value while validating the relationships

- filip/clients/ngsi_ld/cb.py
> erorr in make tenant function

- setup.py
> fix: add encoding in setup.py

- CHANGELOG.md
- README.md
- filip/clients/ngsi_v2/cb.py
- filip/clients/ngsi_v2/iota.py
- tests/clients/test_ngsi_v2_cb.py
> 413 adapt the patch entity function in v2 to align with the orion api

- filip/clients/ngsi_ld/cb.py
- tests/clients/test_ngsi_ld_entity_batch_operation.py
> Add context provision check in entity batch operation of cb ld

- CHANGELOG.md
- examples/ngsi_ld/e01_ngsi_ld_context_basics.py
- examples/ngsi_ld/e02_ngsi_ld_context_relationships.py
- examples/ngsi_ld/e03_ngsi_ld_context_subscriptions_http.py
- examples/ngsi_ld/e04_ngsi_ld_context_subscriptions_mqtt.py
- examples/ngsi_ld/e05_ngsi_ld_quantumleap.py
- examples/ngsi_ld/e06_ngsi_ld_use_case_models.py
- examples/ngsi_ld/e06_ngsi_v2_use_case_models.py
- examples/ngsi_ld/e07_ngsi_ld_context_tenant.py
- examples/ngsi_ld/e08_ngsi_ld_notification_based_command.py
- examples/ngsi_ld/e09_ngsi_ld_sysattrs.py
- filip/clients/ngsi_ld/cb.py
- filip/clients/ngsi_v2/quantumleap.py
- filip/config.py
- filip/models/ngsi_ld/context.py
- filip/models/ngsi_ld/subscriptions.py
- tests/clients/test_ngsi_ld_cb_kv.py
I have unfortunately wasted a lot of time trying to figure out how to circumvent the custom model property type issues (e06 use case models), and have only annotated the examples i wrote from scratch. I've also felt that the JSON-LD context example is a bit on the light side so i added an example about multi-tenancy.
You will notice that there are some source code files that have been modified, this is to make the quantumleap example work with ld, as a model for a manual QL notification does not exist in ld, so i added it.
> NGSI LD examples

- .github/workflows/unittest.yml
- CHANGELOG.md
- README.md
- filip/clients/ngsi_v2/cb.py
- filip/models/ngsi_v2/subscriptions.py
- filip_unittest/docker/docker-compose.yml
- tests/clients/test_ngsi_ld_cb_kv.py
- tests/clients/test_ngsi_ld_entity_batch_operation.py
- tests/clients/test_ngsi_v2_cb.py
> 440 add lastfailure and lastsuccess to subscription model

- CHANGELOG.md
- examples/ngsi_v2/e15_ngsi_v2_forecast_data_saving.py
- filip/clients/ngsi_ld/cb.py
- filip/models/ngsi_ld/context.py
- tests/clients/test_ngsi_ld_cb.py
> add entityld/keyvalue conversion and tests, relationship validation

- CHANGELOG.md
- filip/clients/ngsi_ld/cb.py
- tests/clients/test_ngsi_ld_cb.py
> feat: add pagination for get entity list
